# Common config items, which will be used for all the areas/products
# if product-by-product exceptions are specified
common:
  # Absolute path to directory where the images are saved
  output_dir:
    /tmp
  # For some satellites it's possible to use external calibration.  If
  # you have those data, set to true.  Can be commented out, defaults
  # to false.
  use_extern_calib: false
  # Pattern for file names.
  fname_pattern:
    "{time:%Y%m%d_%H%M}_{platform_name}_{areaname}_{productname}.{format}"
  # Save images in the listed formats.  If "tif" is specified,
  # gdal-python is needed for saving geotiff images.
  formats:
    - png
    - tif

# Process areas "eurol" and "euron1" as one group
# Even for one area, list it as one group!
groups:
  europe:
    - eurol
    - euron1

product_list:
  eurol: # area ID used to get the area definition
    areaname: eurol # name used in filename composing
    # min_coverage: 25
    # srch_radius: 10000
    # In YAML, it is possible to use tags so the same thing can be
    # used again without writing it out
    products: &eurol_products
      - vis08: # product ID for getting the compositor
        productname: vis08 # name used in filename composing
        sunzen_day_maximum: 100
        # sunzen_lonlat: [25, 60]
        # sunzen_night_minimum: 80
        # We've set the output directory in global scope, so no need here
        # output_dir:
        #   /tmp/
        formats:
          - png
          - tif
          # - nc
        # NOTE: different pattern, we'll override the global value for
        # this product
        fname_pattern: "{time:%Y%m%d%H%M}_{platform_name}_{areaname}_{productname}.{format}"
        
      - ir108: # product ID for getting the compositor
        productname: ir108 # name used in filename composing
        sunzen_night_minimum: 80
        # sunzen_lonlat: [25, 60]
        # Here we'll override the output directory, and use
        # year/month/day structure
        # NOTE! The directory needs to exist
        output_dir: "/tmp/{time:%Y/%m/%d}"
        formats:
          - png
          - tif
          # - nc
        fname_pattern: "{time:%Y%m%d_%H%M}_{platform_name}_{areaname}_{productname}.{format}"
        
  euron1: # area ID used to get the area definition
    areaname: euron1 # name used in filename composing
    # See the product list for "eurol" area, we'll use the same here
    products: *eurol_products
